-- BẢNG MẶT HÀNG

USE KARAOKEMANAGEMENT;
CREATE TABLE SANPHAM(
	ID_SanPham 			INT NOT NULL AUTO_INCREMENT,
	TenSanPham 			VARCHAR(50) NOT NULL,
	DonVi	 			VARCHAR(50) NOT NULL,
	SoLuong 			INT,
	GiaNhap 			INT,
    GiaBan				INT,
	PRIMARY KEY (ID_SanPham)
);