-- BẢNG TÀI KHOẢN

USE KARAOKEMANAGEMENT;
CREATE TABLE TAIKHOAN(
	Username 		VARCHAR(50) NOT NULL,
	MatKhau 		VARCHAR(100) NOT NULL,
	Ten 			VARCHAR(50) NOT NULL,
	SoDienThoai 	VARCHAR(50) NOT NULL,
	LoaiTaiKhoan 	VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (Username)
);